#!/usr/bin/env python3
"""Subset Fusion Pixel 12px (TakWolf, SIL OFL 1.1) to the characters the 长寿图鉴 actually shows.

Writes src/client/engage/font.ts, exporting CODEX_FONT_CSS: one @font-face for "LpCodexPixel" with the subset as a
base64 woff2 data URL. Rerun after data/codex/v3/library.json is rebuilt (new cards bring new characters):

    <python with fonttools + brotli> scripts/codex-font.py [--extra FILE ...]

Characters come from: every string in data/codex/v3/{library,content.zh,experiments.zh}.json; every CJK character
and every full-width or CJK punctuation mark in src/client/engage/*.ts, src/client/styles/codex.ts, src/engage/*.ts
and src/ux/plain.ts; the
preview fixtures (preview/fixtures/codex*.json); printable ASCII; common CJK punctuation; and any --extra files.
The licence ships as data/codex/v3/fonts/OFL.txt.
"""

import base64
import glob
import io
import json
import os
import re
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SOURCE_CSS = os.path.join(ROOT, 'preview', 'codex', 'fonts', 'font.css')
OUT = os.path.join(ROOT, 'src', 'client', 'engage', 'font.ts')

JSON_SOURCES = [
    'data/codex/v3/library.json',
    'data/codex/v3/content.zh.json',
    'data/codex/v3/experiments.zh.json',
    'preview/fixtures/codex.json',
    'preview/fixtures/codex-library.json',
]
CODE_SOURCES = ['src/client/engage/*.ts', 'src/client/styles/codex.ts', 'src/engage/*.ts', 'src/ux/plain.ts']
# Not a source: the generated file itself holds only base64.
SKIP = {os.path.relpath(OUT, ROOT)}

ASCII = ''.join(chr(c) for c in range(0x20, 0x7f))
PUNCT = '，。、；：？！…—–·「」『』（）《》〈〉【】〔〕“”‘’％＋－＝／～　→←↑↓×÷±≥≤≈°℃■□○●▲△★☆✓✕'
# CJK ideographs, kana, full-width forms, CJK symbols and punctuation, general punctuation and arrows.
WANTED = re.compile(r'[\u00a0-\u00ff\u0370-\u03ff\u2000-\u206f\u2190-\u21ff\u2200-\u22ff\u25a0-\u25ff\u2600-\u26ff\u2700-\u27bf\u3000-\u303f\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uff00-\uffef]')


def strings(value):
    if isinstance(value, str):
        yield value
    elif isinstance(value, dict):
        for key, item in value.items():
            yield key
            yield from strings(item)
    elif isinstance(value, list):
        for item in value:
            yield from strings(item)


def collect(extra):
    chars = set(ASCII) | set(PUNCT)
    used = []
    for rel in JSON_SOURCES:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        with open(path, encoding='utf-8') as handle:
            data = json.load(handle)
        for text in strings(data):
            chars.update(text)
        used.append(rel)
    for pattern in CODE_SOURCES:
        for path in sorted(glob.glob(os.path.join(ROOT, pattern))):
            rel = os.path.relpath(path, ROOT)
            if rel in SKIP:
                continue
            with open(path, encoding='utf-8') as handle:
                chars.update(WANTED.findall(handle.read()))
            used.append(rel)
    for path in extra:
        with open(path, encoding='utf-8') as handle:
            text = handle.read()
        try:
            for item in strings(json.loads(text)):
                chars.update(item)
        except ValueError:
            chars.update(text)
        used.append(path)
    chars.discard('\n')
    chars.discard('\r')
    chars.discard('\t')
    return chars, used


def source_font():
    with open(SOURCE_CSS, encoding='utf-8') as handle:
        css = handle.read()
    match = re.search(r'base64,([A-Za-z0-9+/=]+)', css)
    if not match:
        raise SystemExit(f'no base64 font in {SOURCE_CSS}')
    return base64.b64decode(match.group(1))


def main(argv):
    extra = []
    args = list(argv)
    while args:
        arg = args.pop(0)
        if arg == '--extra' and args:
            extra.extend(sorted(glob.glob(args.pop(0))))
        else:
            raise SystemExit(f'unknown argument: {arg}')
    chars, used = collect(extra)
    raw = source_font()
    font = TTFont(io.BytesIO(raw))
    cmap = font.getBestCmap()
    have = sorted(c for c in chars if ord(c) in cmap)
    missing = sorted(c for c in chars if ord(c) not in cmap and not c.isspace())
    options = subset.Options()
    options.flavor = 'woff2'
    options.layout_features = ['*']
    options.name_IDs = ['*']
    options.name_legacy = True
    options.notdef_outline = True
    options.drop_tables = ['DSIG']
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=[ord(c) for c in have])
    subsetter.subset(font)
    out = io.BytesIO()
    font.flavor = 'woff2'
    font.save(out)
    woff2 = out.getvalue()
    b64 = base64.b64encode(woff2).decode('ascii')
    ts = (
        '// Generated by scripts/codex-font.py: do not edit. Fusion Pixel 12px (TakWolf), SIL Open Font License 1.1\n'
        '// (data/codex/v3/fonts/OFL.txt), subset to the characters the 长寿图鉴 shows. Rerun the script after the\n'
        '// library is rebuilt.\n'
        f'// {len(have)} characters, {len(woff2)} bytes woff2.\n\n'
        'export const CODEX_FONT_CSS = `@font-face { font-family: "LpCodexPixel"; '
        f'src: url(data:font/woff2;base64,{b64}) format("woff2"); font-display: swap; }}`\n'
    )
    with open(OUT, 'w', encoding='utf-8') as handle:
        handle.write(ts)
    print(f'{len(have)} characters from {len(used)} files -> {os.path.relpath(OUT, ROOT)}')
    print(f'woff2 {len(woff2)} bytes ({len(woff2) / 1024:.1f} KB), base64 {len(b64)} bytes; full font {len(raw)} bytes')
    if missing:
        print(f'not in the font ({len(missing)}): {"".join(missing)}')


if __name__ == '__main__':
    main(sys.argv[1:])
